# Generated by Django 5.2.15 on 2026-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts', '0002_delete_follow'),
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='prevent_self_follow'),
        ),
    ]
