# Generated by Django 5.2.15 on 2026-07-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts', '0002_delete_follow'),
        ('users', '0003_rename_customuser_user_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
